title: Gaetano Piazzolla
description: GitHub Page Website - Made with Jekyll and Minima Theme.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://gaetanopiazzolla.github.io # the base hostname & protocol for your site, e.g. http://example.com
github_username: GaetanoPiazzolla

plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: jekyll/minima

minima:
  skin: classic
  social_links:
    - { platform: github,  user_url: "https://github.com/GaetanoPiazzolla" }
    - { platform: stackoverflow, user_url: "https://stackoverflow.com/users/2768318/gaetano-piazzolla" }

google_analytics: G-PPMZFEW9CK
