title: Gaetano Piazzolla - Java && More
description: Technical Articles About Java, Spring, Web App Development and More
baseurl: "" # the subpath of your site, e.g. /blog
url: http://gaetanopiazzolla.github.io # the base hostname & protocol for your site, e.g. http://example.com
github_username: GaetanoPiazzolla

plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: jekyll/minima

minima:
  skin: classic

# Define which pages should appear in the navigation
header_pages:
  - pages/about.markdown

show_excerpts: true

google_analytics: G-PPMZFEW9CK

# Collection for external articles
collections:
  external_articles:
    output: false
