title: Java && More
description: Technical Articles About Java, Spring, Web App Development and More
baseurl: "" # the subpath of your site, e.g. /blog
url: http://gaetanopiazzolla.github.io # the base hostname & protocol for your site, e.g. http://example.com
github_username: GaetanoPiazzolla

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

remote_theme: jekyll/minima

minima:
  skin: classic

# Define which pages should appear in the navigation
header_pages:
  - pages/about.markdown

show_excerpts: true

google_analytics: G-PPMZFEW9CK

google_adsense: ca-pub-4407573159416265

# Ad slot IDs (you'll get these from Google AdSense after approval)
# google_adsense_slots:
#   top_article: "XXXXXXXXXX"
#   bottom_article: "XXXXXXXXXX" 
#   in_article: "XXXXXXXXXX"
#   sidebar: "XXXXXXXXXX"
#   home_top: "XXXXXXXXXX"

# Collection for external articles
collections:
  external_articles:
    output: false
